export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST';
export const UPDATE_MULTIPLE_TASKS_REQUEST = 'UPDATE_MULTIPLE_TASKS_REQUEST';
export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
